tasks:
  - name: App
    init: >
      yarn &&
      gp sync-done install
    command: REACT_APP_PROVIDER=$(gp url 8545) yarn start
  - name: Chain
    init: gp sync-await install
    command: yarn chain
    openMode: split-right
  - name: Deployment
    init: gp sync-await install
    command: sleep 3 && yarn deploy
    openMode: split-right
ports:
  - port: 3000 
    onOpen: open-preview
  - port: 8545
    onOpen: ignore
    visibility: public
  - port: 7700
    onOpen: ignore
    visibility: public
vscode:
  extensions:
    - esbenp.prettier-vscode
    - juanblanco.solidity