/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    HorizontalLine: {
      address: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
      abi: [
        {
          inputs: [
            {
              internalType: "contract IKilim",
              name: "_kilim",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_startX",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_endX",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_y",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_state",
              type: "bool",
            },
          ],
          name: "draw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
    Kilim: {
      address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "x",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "y",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "state",
              type: "bool",
            },
          ],
          name: "Set",
          type: "event",
        },
        {
          inputs: [],
          name: "HEIGHT",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "WIDTH",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_x",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_y",
              type: "uint256",
            },
          ],
          name: "getState",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getStates",
          outputs: [
            {
              internalType: "bool[100][162]",
              name: "",
              type: "bool[100][162]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_x",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_y",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_state",
              type: "bool",
            },
          ],
          name: "setState",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
